# Generated by Django 5.2.6 on 2025-09-27 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_object_ready_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ava_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступное кол-во'),
        ),
    ]
