# Generated by Django 5.2.6 on 2025-09-27 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_product_ava_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='completed_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Произведённое кол-во'),
        ),
    ]
