# Generated by Django 5.2.6 on 2025-09-27 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_product_completed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='ava_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступное кол-во'),
        ),
    ]
